---
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      # - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
      # - id: name-tests-test
    #   - id: no-commit-to-branch
    #     args:
    #       - --branch
    #       - develop
    #       - --branch
    #       - staging
    #       - --branch
    #       - prod
      - id: requirements-txt-fixer
        # files: requirements.*\.txt(\.tmpl){0,1}$
      - id: trailing-whitespace

#   - repo: https://gitlab.com/pycqa/flake8
#     rev: 3.8.3
#     hooks:
#       - id: flake8
#         additional_dependencies: [flake8-typing-imports==1.6.0]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
      - id: autopep8

  # - repo: https://github.com/pre-commit/pre-commit
  #   rev: v2.6.0
  #   hooks:
  #   - id: validate_manifest

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v2.6.2
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py36-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v1.10.0
  #   hooks:
  #   - id: setup-cfg-fmt

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.782
  #   hooks:
  #   - id: mypy
  #     exclude: ^testing/resources/

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
